[package]
name = "PrisonYard"
version = "0.1.0"
edition = "2021"

[dependencies]
Justice = { path = "../Justice" }
chrono = "0.4.39"
rand = "0.8.5"
rocket = {version = "0.5.1", features = ["json"]}
rusqlite = {version = "0.32.1", features = ["bundled"]}
serde_json = "1.0.135"
turbosql = "0.11.0"
